### ISSUE TITLE
Clarify license of FMUs generated with Simulix

### ISSUE THREAD

**Issue by chrbertsch** [Kvixen/Simulix#21]
Currently the Simulix project is distributed under the GPL.
The GPL license might inhibit the industrial usage of Source Code FMU and for the creation of binary FMU with external code, because of the copyleft effect: to my understanding one would have to put the whole model code from which the FMU is created unter GPL license.
So it would be very beneficial to exclude the files that are included in an FMU generated by Simulix and the generated FMUs from the GPL license.
It is also recommended to include the license for the FMU in the documentation folder of the FMU.
Thanks in advance for considering this.

**Comment by beutlich** [comment]
To my understanding, the used third-party components (cJSON, FMUSDK, Simulink Coder, FMI itself) are not problematic.

Note the license expcetion in
https://github.com/Kvixen/Simulix/blob/9e4eafa5214f5d0b333b1cd7c189895cd9f1b7bd/templates/Simulix_cg_license.txt#L23-L30
which somehow illustrates the GPL issue. Provided, that there is a Simulix v1.0 (which is not the case right now), I understand this, that FMUs can be distributed under any license.

Furthermore, it would be nice, if Simulix_dllmain_template.c gets a copyright disclaimer, since it is distributed as part of the generated FMU.

**Comment by beutlich** [comment]
Reading further, especially https://www.gnu.org/licenses/gpl-faq.html#GPLOutput and https://www.gnu.org/licenses/gpl-faq.html#WhatCaseIsOutputGPL, there is no issue to have a GPLed tool chain that outputs FMUs under any user-chosen license.

> So it would be very beneficial to exclude the files that are included in an FMU generated by Simulix and the generated FMUs from the GPL license.

This is the case. But should be clarified by a copyright disclaimer and license header of Simulix_dllmain_template.c, which is the only Simulix file, that is part of the source-code FMU.

> It is also recommended to include the license for the FMU in the documentation folder of the FMU.

This is the case for fmusdk_license.txt. But should also add a Simulix_license.txt (different from Simulix_cg_license.txt).

**Comment by Kvixen** [comment]
Newest release of Simulix should resolve the license issues.
